### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by intelysol** [Technus/AS73211_Lib#1]
hello dear 

can you write an example program for Arduino with this library, 

I am working on a project using your library but  didn't get the correct XYZ values

thanks
Shahid Mehmood
iss_shahid@yahoo.com

**Comment by Technus** [comment]
The sensor requires calibration to be really precise, but it also requires specific conditions to be used properly.

**Comment by Technus** [comment]
The light incidence angle must be low iirc <15deg, and the light source should be broad band, so it has problems with things like LED, CCFL, Fluorescent etc. All light sources introduce error, it works best with things like regular light bulbs and sunlight.

**Comment by Technus** [comment]
Other thing is i have no clue how to properly convert the reading to CIE XYZ values, as i can never get the scale right, so i just use some reference point. Besides that the lib should expose methods to get all the gains and stuff. And in theory i added the Ee calculation as in datasheet.

**Comment by Technus** [comment]
Also eventually i hooked the sensor to raspberry pi zero and hooked it to pc over wifi,might publish that code tho.

**Comment by Technus** [comment]
https://github.com/Technus/XYZRGBLED
https://github.com/Technus/XYZOverWifi
