### ISSUE TITLE
Does this library work?

### ISSUE THREAD

**Issue by Jakobovski** [Technus/AS73211_Lib#2]
Hey Thanks for publishing this code! 

I am looking to use a AS73211 with my Arduino and I am wondering if this code is fully functional?

**Comment by antojijo** [comment]
@Jakobovski did u tested this library????

**Comment by Jakobovski** [comment]
@antojijo  i did not test it

**Comment by antojijo** [comment]
@Jakobovski board will receive soon if possible I will test and post the results.

**Comment by Jakobovski** [comment]
@antojijo  Great! Thank you.

**Comment by DimiRom** [comment]
Thanks for publishing this code! I tested the code and it seems to work fine. I have only one problem, the value of X,Y,Z saturates at 15 bits (32768) and not 16 bits (65536). Is it possible to correct that?

**Comment by Technus** [comment]
Should, IIRC used it once or twice

**Comment by Technus** [comment]
See: https://github.com/Technus/AS73211_Lib/issues/3
